version: '3'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt 
    image: koenkk/zigbee2mqtt
    restart: always
    volumes:
      - ~/anni/zigbee2mqtt:/app/data/
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - TZ=Europe/Berlin
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ~/anni/mosquitto/config:/mosquitto/config/
      - ~/anni/mosquitto/data:/mosquitto/data/
      - ~/anni/mosquitto/log:/mosquitto/log/
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      - TZ=Europe/Berlin
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    restart: always
    volumes:
      - ~/anni/home-assistant:/config
    ports:
      - 8123:8123
    environment:
      - TZ=Europe/Berlin

networks:
  default:
    external:
      name: anni
