version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ~/dev/src/Anni/home-assistant/docker-volume:/config
    environment:
      - TZ=Europe/Berlin
    restart: always
    network_mode: host
